INSERT INTO PUBLIC.VOITURE (ID, MARQUE, PLATE_NUMBER, CLIENT_ID) VALUES (1, 'Renault', '04AH91', 1);
INSERT INTO PUBLIC.VOITURE (ID, MARQUE, PLATE_NUMBER, CLIENT_ID) VALUES (2, 'Audi', '34GA36', null);
INSERT INTO PUBLIC.VOITURE (ID, MARQUE, PLATE_NUMBER, CLIENT_ID) VALUES (3, 'Mercedes', '53KN74', null);
INSERT INTO PUBLIC.VOITURE (ID, MARQUE, PLATE_NUMBER, CLIENT_ID) VALUES (4, 'Fiat', '48NA01', null);
INSERT INTO PUBLIC.VOITURE (ID, MARQUE, PLATE_NUMBER, CLIENT_ID) VALUES (5, 'Citroën', '62AD49', null);
INSERT INTO PUBLIC.VOITURE (ID, MARQUE, PLATE_NUMBER, CLIENT_ID) VALUES (6, 'Mercedes', '82HG30', null);